import type { relationship as fa } from '../fa/relationship';
import type { Strings } from '../types';

export const relationship: Strings<typeof fa> = {
  units: {
    year_one: '{{count}} year',
    year_other: '{{count}} years',
    month_one: '{{count}} month',
    month_other: '{{count}} months',
    day_one: '{{count}} day',
    day_other: '{{count}} days',
    and: ' and ',
    comma: ', ',
  },
  clock: {
    title: 'Time together',
    you: 'You',
    partner: 'Partner',
    y: 'Years',
    mo: 'Months',
    d: 'Days',
    h: 'Hours',
    mi: 'Minutes',
    s: 'Seconds',
    ms: 'Milliseconds',
    since: 'Since {{date}}',
    summary: 'Time together: {{y}} years, {{mo}} months, {{d}} days',
    open: 'Open Rel Clock',
  },
  home: {
    you: 'You',
    partner: 'Partner',
    notJoined: 'Not joined yet',
    invited: 'Invited',
    inviteTitle: "Your partner hasn't joined yet.",
    inviteBody: 'Our thread starts the day you both share how you are.',
    resend: 'Send the invitation again',
  },
  eyebrow: 'Relationship',
  start: {
    title: 'Start your relationship.',
    body: "Both people's phones and RelTimes connect to the same relationship.",
    create: 'Create a new relationship',
    createHint: "If your partner doesn't have RelTime Mobile yet",
    join: 'Join with an invite code',
    joinHint: 'If your partner created it and invited you',
    note: 'You can end the relationship later from More without losing your account.',
    endedByPartner:
      'Your partner ended the relationship. You can create a new one or join with an invite code.',
    endedByYou: 'The relationship has ended. Your account is still here.',
  },
  create: {
    title: 'When did you get together?',
    body: 'Your time together is counted from this moment.',
    date: 'Start date',
    time: 'Start time',
    calendar: 'Calendar',
    jalali: 'Jalali',
    gregorian: 'Gregorian',
    timeZone: 'Time zone',
    preview: 'Preview',
    sharedNote:
      "The start date is shared by both of you; changing it later needs your partner's approval.",
    future: "The start date can't be in the future.",
    submit: 'Create relationship',
    done: 'Done',
    year: 'Year',
    month: 'Month',
    day: 'Day',
    hour: 'Hour',
    minute: 'Minute',
    increase: 'Increase {{unit}}',
    decrease: 'Decrease {{unit}}',
    zoneRow: '{{city}} · {{offset}}',
  },
  invite: {
    title: 'Invite your partner.',
    body: 'Send this code to your partner. It works once, for 7 days.',
    codeLabel: 'Invite code',
    copy: 'Copy code',
    copied: 'Code copied',
    share: 'Send invitation',
    shareMessage: 'Join our relationship on RelTime. Invite code: {{code}}',
    waiting: 'Waiting for your partner to join…',
    joined: 'Your partner joined.',
    later: "I'll invite later",
    continue: 'Continue',
    expires: 'Valid until {{date}}',
  },
  join: {
    title: 'Enter the invite code.',
    body: 'Enter the 8-character code your partner sent you.',
    label: 'Invite code',
    placeholder: '7K4P 9RM2',
    preview: 'Relationship with {{name}} · since {{date}} · {{elapsed}}',
    previewUnnamed: 'Relationship since {{date}} · {{elapsed}}',
    consent: 'By joining, status, notes and occasions are shared between the two of you.',
    submit: 'Join relationship',
    noCode: "I don't have a code",
    checking: 'Checking the code…',
    errors: {
      invite_invalid: "We couldn't find that code. Check it and try again.",
      invite_expired: 'This code has expired. Ask your partner for a new one.',
      invite_used: 'This code was already used. Ask your partner for a new one.',
      already_in_relationship:
        "You're already in a relationship. End it from More before joining another.",
    },
  },
  details: {
    title: 'Relationship',
    since: 'Since {{date}} · {{time}}',
    together: '{{elapsed}} together',
    timeTogether: 'Time together',
    startDate: 'Start date',
    startTime: 'Start time',
    calendar: 'Calendar',
    timeZone: 'Time zone',
    approvalNote: "Changing these needs your partner's approval.",
    members: 'Members',
    youSuffix: '(you)',
    joined: 'Since {{date}}',
    unnamed: 'No name',
    partner: 'Partner',
    invited: 'Invited',
    showInvite: 'Show invite code',
    id: 'Relationship ID',
    copyId: 'Copy ID',
    idCopied: 'ID copied',
    end: 'End relationship',
    confirmTitle: 'End the relationship?',
    confirmBody:
      'Shared time, statuses and notes close for both of you, and RelTimes detach. Your account stays, and your partner is notified.',
    confirm: 'End relationship',
    cancel: 'Cancel',
  },
  ready: {
    label: 'Relationship',
    value: 'Since {{date}}',
  },
  more: {
    row: 'Relationship',
  },
  zones: {
    'Asia/Tehran': 'Tehran',
    'Asia/Dubai': 'Dubai',
    'Asia/Istanbul': 'Istanbul',
    'Europe/Istanbul': 'Istanbul',
    'Europe/London': 'London',
    'Europe/Berlin': 'Berlin',
    'Europe/Paris': 'Paris',
    'Europe/Stockholm': 'Stockholm',
    'America/New_York': 'New York',
    'America/Toronto': 'Toronto',
    'America/Los_Angeles': 'Los Angeles',
    'Australia/Sydney': 'Sydney',
    UTC: 'UTC',
  },
};
