export const onboarding = {
  progress: {
    step: 'مرحله {{step}} از ۴',
    complete: 'راه‌اندازی کامل شد',
  },
  later: 'بعداً',
  welcome: {
    you: 'شما',
    partner: 'همراه',
    dialUnit: 'سال',
    headline: 'زمان مشترک شما، همیشه پیش روی شما.',
    body: 'RelTime Mobile گوشی شما را به رابطه‌تان در Relationship OS وصل می‌کند؛ با RelTime روی میز یا بدون آن.',
    language: 'زبان',
    /** Read in the chosen language, so choosing English says "Continue in English". */
    continue: 'ادامه',
  },
  account: {
    eyebrow: 'حساب',
    title: 'وارد حساب Relationship OS شوید.',
    body: 'اگر حساب ندارید، با همین شماره ساخته می‌شود.',
    phoneLabel: 'شماره‌ی تلفن همراه',
    phonePlaceholder: '0912 345 6789',
    phoneHint: 'کدی یک‌بارمصرف برایتان پیامک می‌کنیم؛ رمزی لازم نیست.',
    requestCode: 'دریافت کد ورود',
    codeLabel: 'کد ورود',
    codeSentPrefix: 'کد ۶ رقمی به ',
    codeSentSuffix: ' پیامک شد.',
    changeNumber: 'تغییر شماره',
    resend: 'ارسال دوباره',
    resendIn: 'ارسال دوباره · {{time}}',
    resent: 'کد تازه فرستاده شد.',
    signIn: 'ورود',
    errors: {
      phoneInvalid: 'این شماره درست نیست. شماره‌ی همراه را مثل ۰۹۱۲ ۳۴۵ ۶۷۸۹ وارد کنید.',
      codeInvalid: 'این کد درست نیست. دوباره امتحان کنید.',
      codeExpired: 'این کد دیگر معتبر نیست. کد تازه بگیرید.',
      attemptsExceeded: 'چند بار کد اشتباه وارد شد. کد تازه بگیرید.',
      rateLimited: 'درخواست کد زیاد بود. کمی بعد دوباره تلاش کنید.',
    },
  },
  name: {
    eyebrow: 'حساب',
    title: 'همراهتان شما را با چه نامی ببیند؟',
    body: 'این نام در صفحه‌های مشترک به همراهتان نشان داده می‌شود.',
    label: 'نام',
    placeholder: 'مثلاً محمد',
    continue: 'ادامه',
    tooLong: 'نام حداکثر ۴۰ نویسه است.',
  },
  ready: {
    headline: 'اتصال انجام شد.',
    subline: 'RelTime و این گوشی آماده‌اند.',
    headlinePhone: 'همه‌چیز آماده است.',
    sublinePhone: 'این گوشی آماده است.',
    summary: 'خلاصه‌ی راه‌اندازی',
    action: 'مشاهده زمان ما',
  },
};
