export const relationship = {
  units: {
    year_one: '{{count}} سال',
    year_other: '{{count}} سال',
    month_one: '{{count}} ماه',
    month_other: '{{count}} ماه',
    day_one: '{{count}} روز',
    day_other: '{{count}} روز',
    /** Joins the last two parts: «۵ سال، ۶ ماه و ۱۲ روز». */
    and: ' و ',
    comma: '، ',
  },
  clock: {
    title: 'زمان ما',
    you: 'شما',
    partner: 'همراه',
    y: 'سال',
    mo: 'ماه',
    d: 'روز',
    h: 'ساعت',
    mi: 'دقیقه',
    s: 'ثانیه',
    ms: 'هزارم ثانیه',
    since: 'از {{date}}',
    summary: 'زمان ما: {{y}} سال، {{mo}} ماه، {{d}} روز',
    open: 'باز کردن زمان ما',
  },
  home: {
    you: 'شما',
    partner: 'همراه',
    notJoined: 'هنوز نپیوسته',
    invited: 'دعوت شده',
    inviteTitle: 'همراهتان هنوز نپیوسته است.',
    inviteBody: 'رشته‌ی ما از روزی آغاز می‌شود که هر دو حالتان را بگذارید.',
    resend: 'ارسال دوباره‌ی دعوت‌نامه',
  },
  eyebrow: 'رابطه',
  start: {
    title: 'رابطه‌تان را آغاز کنید.',
    body: 'گوشی‌ها و RelTimeهای هر دو نفر به یک رابطه وصل می‌شوند.',
    create: 'ساختن رابطه‌ی تازه',
    createHint: 'اگر همراهتان هنوز RelTime Mobile ندارد',
    join: 'پیوستن با کد دعوت',
    joinHint: 'اگر همراهتان رابطه را ساخته و شما را دعوت کرده',
    note: 'رابطه را بعداً هم می‌توانید از «بیشتر» پایان دهید؛ حسابتان سر جایش می‌ماند.',
    endedByPartner:
      'همراهتان رابطه را پایان داد. می‌توانید رابطه‌ی تازه‌ای بسازید یا با کد دعوت بپیوندید.',
    endedByYou: 'رابطه پایان یافت. حسابتان سر جایش است.',
  },
  create: {
    title: 'از کی با هم هستید؟',
    body: 'زمان ما از همین لحظه شمرده می‌شود.',
    date: 'تاریخ آغاز',
    time: 'ساعت آغاز',
    calendar: 'تقویم',
    jalali: 'جلالی',
    gregorian: 'میلادی',
    timeZone: 'منطقه‌ی زمانی',
    preview: 'پیش‌نمایش',
    sharedNote: 'تاریخ آغاز میان شما دو نفر مشترک است و تغییرش بعداً به تأیید همراهتان نیاز دارد.',
    future: 'تاریخ آغاز نمی‌تواند در آینده باشد.',
    submit: 'ساختن رابطه',
    done: 'تأیید',
    year: 'سال',
    month: 'ماه',
    day: 'روز',
    hour: 'ساعت',
    minute: 'دقیقه',
    increase: 'افزایش {{unit}}',
    decrease: 'کاهش {{unit}}',
    zoneRow: '{{city}} · {{offset}}',
  },
  invite: {
    title: 'همراهتان را دعوت کنید.',
    body: 'این کد را برای همراهتان بفرستید. ۷ روز و فقط یک بار کار می‌کند.',
    codeLabel: 'کد دعوت',
    copy: 'کپی کد',
    copied: 'کد کپی شد',
    share: 'ارسال دعوت‌نامه',
    shareMessage: 'در RelTime به رابطه‌مان بپیوند. کد دعوت: {{code}}',
    waiting: 'در انتظار پیوستن همراه…',
    joined: 'همراهتان پیوست.',
    later: 'بعداً دعوت می‌کنم',
    continue: 'ادامه',
    expires: 'معتبر تا {{date}}',
  },
  join: {
    title: 'کد دعوت را وارد کنید.',
    body: 'کد ۸ نویسه‌ای را که همراهتان فرستاده وارد کنید.',
    label: 'کد دعوت',
    placeholder: '7K4P 9RM2',
    preview: 'رابطه با {{name}} · از {{date}} · {{elapsed}}',
    previewUnnamed: 'رابطه از {{date}} · {{elapsed}}',
    consent: 'با پیوستن، حال، یادداشت‌ها و مناسبت‌ها میان شما دو نفر مشترک می‌شود.',
    submit: 'پیوستن به رابطه',
    noCode: 'کد ندارم',
    checking: 'در حال بررسی کد…',
    errors: {
      invite_invalid: 'کدی با این نویسه‌ها پیدا نشد. دوباره بررسی کنید.',
      invite_expired: 'این کد منقضی شده است. از همراهتان کد تازه بخواهید.',
      invite_used: 'این کد پیش‌تر استفاده شده است. از همراهتان کد تازه بخواهید.',
      already_in_relationship: 'شما در رابطه‌ی دیگری هستید. اول آن را از «بیشتر» پایان دهید.',
    },
  },
  details: {
    title: 'رابطه',
    since: 'از {{date}} · {{time}}',
    together: '{{elapsed}} با هم',
    timeTogether: 'زمان با هم',
    startDate: 'تاریخ آغاز',
    startTime: 'ساعت آغاز',
    calendar: 'تقویم',
    timeZone: 'منطقه‌ی زمانی',
    approvalNote: 'تغییر این موارد به تأیید همراهتان نیاز دارد.',
    members: 'اعضا',
    youSuffix: '(شما)',
    joined: 'از {{date}}',
    unnamed: 'بی‌نام',
    partner: 'همراه',
    invited: 'دعوت شده',
    showInvite: 'نمایش کد دعوت',
    id: 'شناسه‌ی رابطه',
    copyId: 'کپی شناسه',
    idCopied: 'شناسه کپی شد',
    end: 'پایان رابطه',
    confirmTitle: 'رابطه پایان یابد؟',
    confirmBody:
      'زمان مشترک، حال‌ها و یادداشت‌ها برای هر دو نفر بسته می‌شود و RelTimeها جدا می‌شوند. حسابتان سر جایش می‌ماند و به همراهتان خبر داده می‌شود.',
    confirm: 'پایان رابطه',
    cancel: 'انصراف',
  },
  ready: {
    label: 'رابطه',
    value: 'از {{date}}',
  },
  more: {
    row: 'رابطه',
  },
  zones: {
    'Asia/Tehran': 'تهران',
    'Asia/Dubai': 'دبی',
    'Asia/Istanbul': 'استانبول',
    'Europe/Istanbul': 'استانبول',
    'Europe/London': 'لندن',
    'Europe/Berlin': 'برلین',
    'Europe/Paris': 'پاریس',
    'Europe/Stockholm': 'استکهلم',
    'America/New_York': 'نیویورک',
    'America/Toronto': 'تورنتو',
    'America/Los_Angeles': 'لس‌آنجلس',
    'Australia/Sydney': 'سیدنی',
    UTC: 'UTC',
  },
};
